# Generated by Django 5.0 on 2023-12-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.BooleanField(default=True),
        ),
    ]
