# Generated by Django 5.0 on 2024-01-02 09:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='variation',
            new_name='variations',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='product_status',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='total_amt',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='paymenttype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='selected_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.address'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.cartorder'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
