# Generated by Django 5.0 on 2024-01-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_variation_productorder_variations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='orderitem',
        ),
    ]
