# Generated by Django 5.0 on 2024-01-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_cartorder_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='paymenttype',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
