# Generated by Django 5.0 on 2024-01-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_cartorder_paymenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='is_ordered',
            field=models.BooleanField(default=True),
        ),
    ]
