# Generated by Django 5.0 on 2024-01-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_cartorder_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
