# Generated by Django 5.0 on 2024-01-18 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_wallethistory_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
