# Generated by Django 5.0 on 2024-01-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_cartitem_coupen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='coupen',
            new_name='coupon',
        ),
    ]
