# Generated by Django 5.0 on 2024-01-23 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0001_initial'),
        ('home', '0007_productattribute_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='title',
        ),
        migrations.AddField(
            model_name='productoffer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category')),
            ],
        ),
    ]
