# Generated by Django 5.0 on 2023-12-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
