# Generated by Django 5.0 on 2023-12-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_productattribute_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
