# Generated by Django 5.0 on 2023-12-29 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cartitem_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
