# Generated by Django 5.0 on 2024-01-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_wishlistitems_wishlistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='old_price',
            field=models.FloatField(default=0),
        ),
    ]
