# Generated by Django 5.0 on 2024-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_productattribute_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='old_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
