# Generated by Django 5.0 on 2024-01-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_productattribute_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_blocked',
            new_name='is_deleted',
        ),
    ]
