# Generated by Django 5.0 on 2024-01-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_is_blocked_category_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_deleted',
            new_name='is_blocked',
        ),
    ]
